fix order of checks

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -19,7 +19,7 @@ jobs:
       - name: Install dependencies
         run: npm install -g pnpm && pnpm install
       - name: Install Playwright Browsers
-        run: npx playwright install firefox --with-deps
+        run: npx playwright install --with-deps
       - name: Run tests
         id: run_playwright_tests
         run: |
@@ -28,12 +28,12 @@ jobs:
             echo "Playwright tests failed due to a snapshot issue."
             echo "SNAPSHOT_DIFFERENCES=true" >> $GITHUB_ENV
             exit 1
-          elif grep -q "failed" output.log; then
-            echo "Playwright tests failed due to a non-snapshot issue."
-            exit 1
           elif grep -q "e2e/global.setup.ts" output.log; then
             echo "Playwright tests failed during global setup."
             echo "SETUP_ERROR=true" >> $GITHUB_ENV
+            exit 1
+          elif grep -q "failed" output.log; then
+            echo "Playwright tests failed due to an issue unrelated to snapshots or global setup."
             exit 1
           fi
         env:
